import React from 'react'
import Header from '../header/Header'
import { pageLinkConstants } from '../constants/pageLinkConstants'

const EventPage = () => {
    return (
        <Header currentPage={pageLinkConstants.HOME}>
        <div>
            1
        </div>
            <div>
                2
            </div>
            <div>
                3
            </div>
            <div>
                4
            </div>
            <div>
                5
            </div>
            <div>
                6
            </div>
            <div>
                7
            </div>
            <div>
                8
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
            <div>
                EventList
            </div>
        </Header>
    )
}

export default EventPage
