class DatabaseConstants:
    USER_TABLE = "Users"
    USER_ID_COL = "id"
    USER_USERNAME_COL = "username"
    USER_PASSWORD_COL = "password"
    EVENT_TABLE = "Event"
    EVENT_ID_COL = "id"
    EVENT_NAME_COL = "name"
    EVENT_DATE_COL = "date"
    EVENT_MIN_COL = "min"
    EVENT_MAX_COL = "max"
    EVENT_NUMBER_COL = "number"
    EVENT_GIFTAS_TABLE = "Giftas"
    EVENT_GIVTAS_EVENT_ID_COL = "eventId"
    EVENT_GIVTA_COL = "giftaId"
    EVENT_GIVTEE_COL = "gifteeId"